repos:
# Common hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: sort-simple-yaml
        files: (ops|backward|op_[a-z_]+)\.yaml$
    -   id: trailing-whitespace
        files: (.*\.(py|bzl|md|rst|c|cc|cxx|cpp|cu|h|hpp|hxx|xpu|kps|cmake|yaml|yml|hook)|BUILD|.*\.BUILD|WORKSPACE|CMakeLists\.txt)$
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.1
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
        name: Tabs remover (C++)
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|xpu|kps)$
        args: [--whitespaces-count, '2']
    -   id: remove-tabs
        name: Tabs remover (Python)
        files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
        args: [--whitespaces-count, '4']
        # Exclude some unit test files that require tabs.
        exclude: |
            (?x)^(
                test/dygraph_to_static/test_legacy_error.py
            )$

# For Python files
-   repo: https://github.com/psf/black.git
    rev: 23.3.0
    hooks:
    -   id: black
        files: (.*\.(py|pyi|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: ["--config=.flake8"]
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.1.5
#     hooks:
#     -   id: ruff
#         args: [--fix, --exit-non-zero-on-fix, --no-cache]

# Document hooks
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.1
    hooks:
    -   id: mdformat
        additional_dependencies: ['mdformat-tables==0.4.0']
